spring:
  devtools:
    livereload:
      port: 9100
  security:
    oauth2:
      authorizationserver:
        endpoint:
          oidc:
            logout-uri: 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: 
        - '*'
        - prometheus
  # Todos los seguimientos deben enviarse a la herramienta de análisis de latencia.   
  tracing:
    sampling:
      probability: 1.0
       
# Para que Exemplars funcione necesitamos depósitos de histogramas
  metrics:
    distribution: 
      percentiles-histogram:
        http:
          server:
            requests: true

# traceID y spanId son claves MDC predefinidas; queremos que los registros las incluyan    
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: 9090
